Exogenous
ricnogfer/pypsa_eur_sec_endogenous_land_transport pull request #19
Opened 2023-05-12 09:51 UTC by ricnogfer

This latest version of the exogenous land transport (toy) model can be launched either using the Python interpreter (i.e. python model.py) or the Snakemake tool (i.e. snakemake -j1). See commits descriptions to get an idea of the developments made in this latest version, as well as the embedded comments in the code.

2023-05-14 08:07 UTC, martavp requested changes
Hi Ricardo, 

Great, I run snakemake in your PR and it works nicely.
See some comments on the review below.  

Let´s go to the next steps. You can implement the transition path. 

When doing that, I suggest you create figures that help us understand if the exogenous transport is working properly, e.g
[ ] Evolution of the land transport demand supplied with electricity and oil throughout the different planning horizons
[ ] Evolution of the number of EVs and ICE cars throughout the different planning horizons
[ ] Evolution of the filling levels of the EV battery for different planning horizons

The idea is to compare these figures with those obtained by Sina 
https://github.com/ricnogfer/pypsa-eur-sec_land_transport/pull/7/files#r1186903622

Please, review @s8au 's PR some of the comments that I made there also apply here.

2023-05-14 08:07 UTC, martavp commented on exogenous/model.py
>      parameters["oil_marginal_cost"] = oil.at["VOM", "value"]
See https://github.com/ricnogfer/pypsa-eur-sec_land_transport/pull/7#discussion_r1186666479

2023-05-14 08:07 UTC, martavp commented on exogenous/model.py
> +    solar_annuity = calculate_annuity(solar.at["lifetime", "value"], 0.05) + solar.at["FOM", "value"] / 100.0   # in percentage
See https://github.com/ricnogfer/pypsa-eur-sec_land_transport/pull/7#discussion_r1186668227

2023-05-14 08:07 UTC, martavp commented on exogenous/model.py
> +    parameters["solar_capital_cost"] = solar_investment * solar_annuity
check how capital costs are defined in the previous link, capital costs should include annualized investment costs + fixed operational and maintenance cost

2023-05-14 08:07 UTC, martavp commented on exogenous/model.py
> +        value = parameters["transport_demand"] * parameters["ICE_shares"][0] / parameters["ICE_efficiency"]
could you estimate, using this load, the number of IEC cars? this could be done with the maximum load value and the 'ICE consumption 1 car' (see https://github.com/ricnogfer/pypsa-eur-sec_land_transport/issues/9)

The final goal is that you can plot the evolution throughout the different planning horizons of the number ICE cars (in your case exogenously determined) and we can compare them with the evolution with the endogenous implementation.

2023-05-14 08:07 UTC, martavp commented on exogenous/model.py
> +                    bus = "bus_oil",
typically we don't include the word 'bus' in the name, so it can be 'oil' instead of 'bus_oil'. This is just a small detail to avoid cumbersome naming

2023-05-15 06:29 UTC, ricnogfer commented on exogenous/model.py
> +                    bus = "bus_oil",
Great that you suggested this change - was actually thinking about it too. I just committed changes to the code with refactored components names (see b36520f5c22c8d9cfa4d15217d7cdb82fc266f91), as well as an update of the network topographical representation with these refactored names (see bf37ea1441a9eaf7db47d31cc0bb42451d0c5100).

2023-05-16 10:48 UTC, ricnogfer commented on exogenous/model.py
>      parameters["oil_marginal_cost"] = oil.at["VOM", "value"]
Fixed - please see commit 647c1c01d259675a14fde46e0d2541408eab02e4.

2023-05-16 10:50 UTC, ricnogfer commented
Implemented transition path - please see commit a125cf5b87480293f7a686565fd96c00260b7a6b.

2023-05-17 09:42 UTC, ricnogfer commented on exogenous/model.py
> +        value = parameters["transport_demand"] * parameters["ICE_shares"][0] / parameters["ICE_efficiency"]
Fixed - please see commit 2519eff40ff14bc7671597a128f033054a85d1f0.

2023-05-17 17:07 UTC, ricnogfer commented on exogenous/model.py
> +    parameters["solar_capital_cost"] = solar_investment * solar_annuity
Fixed (hopefully) - please see commit 871398670e63f3d3add9d90f53220b058110ac3a.

2023-05-29 08:03 UTC, martavp commented on exogenous/model.py
> +    parameters["solar_capital_cost"] = solar_investment * solar_annuity
Yes, it works. 

In the next steps, we want to implement the function prepare_costs() and use it as input for every generator, etc.
https://github.com/PyPSA/pypsa-eur/blob/80eadcf24aea9b1805d8ebfa66de0422e10f0c04/scripts/prepare_sector_network.py#L730

2023-05-29 08:04 UTC, martavp commented on exogenous/model.py
> +                    bus = "bus_oil",
super, it reads clearer this way

2023-05-29 08:05 UTC, martavp commented
I think we can merge this PR

2023-05-29 08:05 UTC, martavp approved these changes

2023-05-29 16:47 UTC, merged

2023-05-31 08:46 UTC, ricnogfer commented on exogenous/model.py
> +    parameters["solar_capital_cost"] = solar_investment * solar_annuity
Good to know that it works!

The _prepare_costs_ function has already been implemented in pull request #28, more precisely in https://github.com/ricnogfer/pypsa-eur-sec_land_transport/blob/e3ee1edcbe4ed6e77f3ac0c7c3e08e085f025220/exogenous/model.py#L445-L496. In addition, this function is being consumed to set up the costs of generators - see https://github.com/ricnogfer/pypsa-eur-sec_land_transport/blob/e3ee1edcbe4ed6e77f3ac0c7c3e08e085f025220/exogenous/model.py#LL269C1-L283C56.

Will check if other network components may have their costs being fed by the _prepare_costs_ function too.